//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Belfast address
		///</summary>
		[ImplementPropertyType("belfastAddress")]
		public string BelfastAddress
		{
			get { return this.GetPropertyValue<string>("belfastAddress"); }
		}

		///<summary>
		/// Boston address
		///</summary>
		[ImplementPropertyType("bostonAddress")]
		public string BostonAddress
		{
			get { return this.GetPropertyValue<string>("bostonAddress"); }
		}

		///<summary>
		/// Description legal
		///</summary>
		[ImplementPropertyType("descriptionLegal")]
		public IHtmlString DescriptionLegal
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionLegal"); }
		}

		///<summary>
		/// Description terms
		///</summary>
		[ImplementPropertyType("descriptionTerms")]
		public IHtmlString DescriptionTerms
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionTerms"); }
		}

		///<summary>
		/// Email error message
		///</summary>
		[ImplementPropertyType("emailErrorMessage")]
		public string EmailErrorMessage
		{
			get { return this.GetPropertyValue<string>("emailErrorMessage"); }
		}

		///<summary>
		/// Email sending message
		///</summary>
		[ImplementPropertyType("emailSendingMessage")]
		public string EmailSendingMessage
		{
			get { return this.GetPropertyValue<string>("emailSendingMessage"); }
		}

		///<summary>
		/// Email success message
		///</summary>
		[ImplementPropertyType("emailSuccessMessage")]
		public string EmailSuccessMessage
		{
			get { return this.GetPropertyValue<string>("emailSuccessMessage"); }
		}

		///<summary>
		/// Image sub text 1
		///</summary>
		[ImplementPropertyType("imageSubText")]
		public string ImageSubText
		{
			get { return this.GetPropertyValue<string>("imageSubText"); }
		}

		///<summary>
		/// Image sub text 2
		///</summary>
		[ImplementPropertyType("imageSubText2")]
		public string ImageSubText2
		{
			get { return this.GetPropertyValue<string>("imageSubText2"); }
		}

		///<summary>
		/// Image sub text 3
		///</summary>
		[ImplementPropertyType("imageSubText3")]
		public string ImageSubText3
		{
			get { return this.GetPropertyValue<string>("imageSubText3"); }
		}

		///<summary>
		/// Image text title
		///</summary>
		[ImplementPropertyType("imageTextTitle")]
		public string ImageTextTitle
		{
			get { return this.GetPropertyValue<string>("imageTextTitle"); }
		}

		///<summary>
		/// Linkedin Account 1
		///</summary>
		[ImplementPropertyType("linkedinAccount1")]
		public string LinkedinAccount1
		{
			get { return this.GetPropertyValue<string>("linkedinAccount1"); }
		}

		///<summary>
		/// Linkedin Account 2
		///</summary>
		[ImplementPropertyType("linkedinAccount2")]
		public string LinkedinAccount2
		{
			get { return this.GetPropertyValue<string>("linkedinAccount2"); }
		}

		///<summary>
		/// Linkedin Account 3
		///</summary>
		[ImplementPropertyType("linkedinAccount3")]
		public string LinkedinAccount3
		{
			get { return this.GetPropertyValue<string>("linkedinAccount3"); }
		}

		///<summary>
		/// Name 1
		///</summary>
		[ImplementPropertyType("name1")]
		public string Name1
		{
			get { return this.GetPropertyValue<string>("name1"); }
		}

		///<summary>
		/// Name 2
		///</summary>
		[ImplementPropertyType("name2")]
		public string Name2
		{
			get { return this.GetPropertyValue<string>("name2"); }
		}

		///<summary>
		/// Name 3
		///</summary>
		[ImplementPropertyType("name3")]
		public string Name3
		{
			get { return this.GetPropertyValue<string>("name3"); }
		}

		///<summary>
		/// Phone from Germany
		///</summary>
		[ImplementPropertyType("phoneFromGermany")]
		public string PhoneFromGermany
		{
			get { return this.GetPropertyValue<string>("phoneFromGermany"); }
		}

		///<summary>
		/// Phone from UK
		///</summary>
		[ImplementPropertyType("phoneFromUK")]
		public string PhoneFromUK
		{
			get { return this.GetPropertyValue<string>("phoneFromUK"); }
		}

		///<summary>
		/// Position 1
		///</summary>
		[ImplementPropertyType("position1")]
		public string Position1
		{
			get { return this.GetPropertyValue<string>("position1"); }
		}

		///<summary>
		/// Position 2
		///</summary>
		[ImplementPropertyType("position2")]
		public string Position2
		{
			get { return this.GetPropertyValue<string>("position2"); }
		}

		///<summary>
		/// Position 3
		///</summary>
		[ImplementPropertyType("position3")]
		public string Position3
		{
			get { return this.GetPropertyValue<string>("position3"); }
		}

		///<summary>
		/// Section description
		///</summary>
		[ImplementPropertyType("sectionDescription")]
		public string SectionDescription
		{
			get { return this.GetPropertyValue<string>("sectionDescription"); }
		}

		///<summary>
		/// Section Description Contact
		///</summary>
		[ImplementPropertyType("sectionDescriptionContact")]
		public string SectionDescriptionContact
		{
			get { return this.GetPropertyValue<string>("sectionDescriptionContact"); }
		}

		///<summary>
		/// Section title
		///</summary>
		[ImplementPropertyType("sectionTitle")]
		public string SectionTitle
		{
			get { return this.GetPropertyValue<string>("sectionTitle"); }
		}

		///<summary>
		/// Section Title Contact
		///</summary>
		[ImplementPropertyType("sectionTitleContact")]
		public string SectionTitleContact
		{
			get { return this.GetPropertyValue<string>("sectionTitleContact"); }
		}

		///<summary>
		/// Service 1
		///</summary>
		[ImplementPropertyType("service1")]
		public IHtmlString Service1
		{
			get { return this.GetPropertyValue<IHtmlString>("service1"); }
		}

		///<summary>
		/// Service 2
		///</summary>
		[ImplementPropertyType("service2")]
		public IHtmlString Service2
		{
			get { return this.GetPropertyValue<IHtmlString>("service2"); }
		}

		///<summary>
		/// Service 3
		///</summary>
		[ImplementPropertyType("service3")]
		public IHtmlString Service3
		{
			get { return this.GetPropertyValue<IHtmlString>("service3"); }
		}

		///<summary>
		/// Service icon 1
		///</summary>
		[ImplementPropertyType("serviceIcon1")]
		public Newtonsoft.Json.Linq.JToken ServiceIcon1
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("serviceIcon1"); }
		}

		///<summary>
		/// Service icon 3
		///</summary>
		[ImplementPropertyType("serviceIcon3")]
		public Newtonsoft.Json.Linq.JToken ServiceIcon3
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("serviceIcon3"); }
		}

		///<summary>
		/// Site Description
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return this.GetPropertyValue<string>("siteDescription"); }
		}

		///<summary>
		/// Site logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public string SiteLogo
		{
			get { return this.GetPropertyValue<string>("siteLogo"); }
		}

		///<summary>
		/// Site Title
		///</summary>
		[ImplementPropertyType("siteTitle")]
		public string SiteTitle
		{
			get { return this.GetPropertyValue<string>("siteTitle"); }
		}

		///<summary>
		/// Team member 1 image
		///</summary>
		[ImplementPropertyType("teamMember1")]
		public string TeamMember1
		{
			get { return this.GetPropertyValue<string>("teamMember1"); }
		}

		///<summary>
		/// Team member 1 details
		///</summary>
		[ImplementPropertyType("teamMember1Details")]
		public string TeamMember1Details
		{
			get { return this.GetPropertyValue<string>("teamMember1Details"); }
		}

		///<summary>
		/// Team member 2 details
		///</summary>
		[ImplementPropertyType("teamMember2Details")]
		public string TeamMember2Details
		{
			get { return this.GetPropertyValue<string>("teamMember2Details"); }
		}

		///<summary>
		/// Team member 2 image
		///</summary>
		[ImplementPropertyType("teamMember2Image")]
		public string TeamMember2Image
		{
			get { return this.GetPropertyValue<string>("teamMember2Image"); }
		}

		///<summary>
		/// Team member 3 details
		///</summary>
		[ImplementPropertyType("teamMember3Details")]
		public string TeamMember3Details
		{
			get { return this.GetPropertyValue<string>("teamMember3Details"); }
		}

		///<summary>
		/// Team member 3 image
		///</summary>
		[ImplementPropertyType("teamMember3Image")]
		public string TeamMember3Image
		{
			get { return this.GetPropertyValue<string>("teamMember3Image"); }
		}

		///<summary>
		/// umbEmailTo: When someone fills out the contact form, where should their e-mail be sent?
		///</summary>
		[ImplementPropertyType("umbEmailTo")]
		public string UmbEmailTo
		{
			get { return this.GetPropertyValue<string>("umbEmailTo"); }
		}
	}
}
